/**
 * autoGenerateDriverSlug.js
 *
 * Called by the "Auto-generate driver slugs" entity automation on Driver create.
 * Also supports being called for a batch backfill via payload.driver_id = '*all'.
 *
 * Logic:
 *   1. If driver already has a canonical_slug AND a slug, do nothing (stable).
 *   2. Build candidate slug from first_name + last_name.
 *   3. Deduplicate by appending numeric suffix if needed.
 *   4. Write slug + canonical_slug + normalized_name + canonical_key.
 *
 * Input (from entity automation payload):
 *   { event: { type, entity_name, entity_id }, data: { ...driver } }
 * Input (manual backfill):
 *   { driver_id: '<id>' | '*all' }
 *
 * Output: { ok, action, driver_id, slug }
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

function toSlug(str) {
  return (str || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .trim() || 'driver';
}

function normalizeName(first, last) {
  return `${first || ''} ${last || ''}`.toLowerCase().trim();
}

async function ensureSlugForDriver(db, driver) {
  // Already has both slug fields — skip (preserve stability)
  if (driver.slug && driver.canonical_slug) {
    return { action: 'skipped', driver_id: driver.id, slug: driver.slug };
  }

  const base = toSlug(`${driver.first_name || ''}-${driver.last_name || ''}`);
  const normalized = normalizeName(driver.first_name, driver.last_name);

  // Find all existing slugs that start with base to detect conflicts
  const allDrivers = await db.entities.Driver.list('-created_date', 500);
  const existingSlugs = new Set(
    allDrivers.filter(d => d.id !== driver.id && d.slug).map(d => d.slug)
  );

  let candidate = base;
  let suffix = 2;
  while (existingSlugs.has(candidate)) {
    candidate = `${base}-${suffix}`;
    suffix++;
  }

  await db.entities.Driver.update(driver.id, {
    slug: candidate,
    canonical_slug: candidate,
    normalized_name: normalized,
    canonical_key: `driver:${candidate}`,
  });

  return { action: 'updated', driver_id: driver.id, slug: candidate };
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    // Auth: accept both user-initiated and automation (service role) calls
    const user = await base44.auth.me().catch(() => null);

    const body = await req.json().catch(() => ({}));

    const db = base44.asServiceRole;

    // --- Entity automation path: payload has event.entity_id ---
    const entityId = body?.event?.entity_id || body?.data?.id || body?.driver_id;

    if (entityId && entityId !== '*all') {
      // Single driver
      const drivers = await db.entities.Driver.filter({ id: entityId }).catch(() => []);
      const driver = drivers?.[0];
      if (!driver) return Response.json({ ok: false, error: 'Driver not found' }, { status: 404 });

      const result = await ensureSlugForDriver(db, driver);
      return Response.json({ ok: true, ...result });
    }

    // --- Batch backfill: driver_id = '*all' or no id given ---
    const allDrivers = await db.entities.Driver.list('-created_date', 1000);
    const missing = allDrivers.filter(d => !d.slug || !d.canonical_slug);

    const results = [];
    for (const driver of missing) {
      const r = await ensureSlugForDriver(db, driver);
      results.push(r);
    }

    return Response.json({
      ok: true,
      total_checked: allDrivers.length,
      updated: results.filter(r => r.action === 'updated').length,
      skipped: results.filter(r => r.action === 'skipped').length,
      results,
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});