/**
 * Centralized access control module for HIJINX platform
 * Defines roles, permissions, and helper functions for authorization
 */

// Tab keys used in the application
export const TAB_KEYS = [
  'overview',
  'eventBuilder',
  'classesSessions',
  'entries',
  'compliance',
  'checkIn',
  'tech',
  'results',
  'pointsStandings',
  'exports',
  'integrations',
  'auditLog',
];

// Action keys used throughout the application
export const ACTION_KEYS = [
  'createEvent',
  'editEvent',
  'deleteEvent',
  'importCSV',
  'syncTiming',
  'publishResults',
  'exportData',
  'createEntry',
  'editEntry',
  'deleteEntry',
  'bulkUpdateEntries',
  'checkInEntry',
  'verifyWaiver',
  'processPayment',
  'assignTech',
  'failTech',
  'passTech',
  'enterResults',
  'editResults',
  'lockResults',
  'publishStandings',
  'recalculateStandings',
  'manageIntegrations',
  'viewAuditLog',
  'createAnnouncement',
  'editAnnouncement',
];

// Role-based permissions configuration
export const ROLE_PERMISSIONS = {
  admin: {
    label: 'Administrator',
    description: 'Full platform access and control',
    tabs: {
      overview: true,
      eventBuilder: true,
      classesSessions: true,
      entries: true,
      compliance: true,
      checkIn: true,
      tech: true,
      results: true,
      pointsStandings: true,
      exports: true,
      integrations: true,
      auditLog: true,
    },
    actions: {
      createEvent: true,
      editEvent: true,
      deleteEvent: true,
      importCSV: true,
      syncTiming: true,
      publishResults: true,
      exportData: true,
      createEntry: true,
      editEntry: true,
      deleteEntry: true,
      bulkUpdateEntries: true,
      checkInEntry: true,
      verifyWaiver: true,
      processPayment: true,
      assignTech: true,
      failTech: true,
      passTech: true,
      enterResults: true,
      editResults: true,
      lockResults: true,
      publishStandings: true,
      recalculateStandings: true,
      manageIntegrations: true,
      viewAuditLog: true,
      createAnnouncement: true,
      editAnnouncement: true,
    },
  },

  race_director: {
    label: 'Race Director',
    description: 'Complete event oversight and management',
    tabs: {
      overview: true,
      eventBuilder: true,
      classesSessions: true,
      entries: true,
      compliance: true,
      checkIn: true,
      tech: true,
      results: true,
      pointsStandings: true,
      exports: true,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: true,
      editEvent: true,
      deleteEvent: false,
      importCSV: true,
      syncTiming: true,
      publishResults: true,
      exportData: true,
      createEntry: true,
      editEntry: true,
      deleteEntry: false,
      bulkUpdateEntries: true,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: true,
      editResults: true,
      lockResults: true,
      publishStandings: true,
      recalculateStandings: true,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: true,
      editAnnouncement: true,
    },
  },

  event_admin: {
    label: 'Event Administrator',
    description: 'Event operations management',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: true,
      entries: true,
      compliance: true,
      checkIn: true,
      tech: true,
      results: true,
      pointsStandings: true,
      exports: true,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: true,
      deleteEvent: false,
      importCSV: true,
      syncTiming: false,
      publishResults: false,
      exportData: true,
      createEntry: true,
      editEntry: true,
      deleteEntry: false,
      bulkUpdateEntries: true,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  registration_staff: {
    label: 'Registration Staff',
    description: 'Entry and registration management',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: true,
      compliance: true,
      checkIn: false,
      tech: false,
      results: false,
      pointsStandings: false,
      exports: true,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: true,
      editEntry: true,
      deleteEntry: false,
      bulkUpdateEntries: true,
      checkInEntry: false,
      verifyWaiver: true,
      processPayment: true,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  checkin_staff: {
    label: 'Check-In Staff',
    description: 'Event check-in and wristband management',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: true,
      tech: false,
      results: false,
      pointsStandings: false,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: true,
      verifyWaiver: true,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  tech_official: {
    label: 'Tech Official',
    description: 'Technical inspection and approval',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: true,
      results: false,
      pointsStandings: false,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: true,
      failTech: true,
      passTech: true,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  scoring_official: {
    label: 'Scoring Official',
    description: 'Results entry and standings management',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: false,
      results: true,
      pointsStandings: true,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: true,
      editResults: true,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: true,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  timing_admin: {
    label: 'Timing Administrator',
    description: 'Timing system and data synchronization',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: true,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: false,
      results: true,
      pointsStandings: false,
      exports: false,
      integrations: true,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: true,
      syncTiming: true,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: true,
      editResults: true,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: true,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  announcer: {
    label: 'Announcer',
    description: 'Race announcements and updates',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: false,
      results: true,
      pointsStandings: true,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: true,
      editAnnouncement: true,
    },
  },

  steward: {
    label: 'Steward',
    description: 'Race oversight and dispute resolution',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: true,
      compliance: true,
      checkIn: false,
      tech: false,
      results: true,
      pointsStandings: true,
      exports: true,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: true,
      createEntry: false,
      editEntry: true,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: true,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  media: {
    label: 'Media',
    description: 'Read-only access for media and public content',
    tabs: {
      overview: true,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: false,
      results: true,
      pointsStandings: true,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  user: {
    label: 'User',
    description: 'Standard user access',
    tabs: {
      overview: false,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: false,
      results: false,
      pointsStandings: false,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },

  public: {
    label: 'Public',
    description: 'Unauthenticated public access',
    tabs: {
      overview: false,
      eventBuilder: false,
      classesSessions: false,
      entries: false,
      compliance: false,
      checkIn: false,
      tech: false,
      results: false,
      pointsStandings: false,
      exports: false,
      integrations: false,
      auditLog: false,
    },
    actions: {
      createEvent: false,
      editEvent: false,
      deleteEvent: false,
      importCSV: false,
      syncTiming: false,
      publishResults: false,
      exportData: false,
      createEntry: false,
      editEntry: false,
      deleteEntry: false,
      bulkUpdateEntries: false,
      checkInEntry: false,
      verifyWaiver: false,
      processPayment: false,
      assignTech: false,
      failTech: false,
      passTech: false,
      enterResults: false,
      editResults: false,
      lockResults: false,
      publishStandings: false,
      recalculateStandings: false,
      manageIntegrations: false,
      viewAuditLog: false,
      createAnnouncement: false,
      editAnnouncement: false,
    },
  },
};

/**
 * Get permissions object for a given role
 * @param {string} role - The user role
 * @returns {object} Permissions object for the role, defaults to 'user' role if not found
 */
export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.user;
}

/**
 * Check if a role has access to a specific tab
 * @param {object} perms - Permissions object from getPermissionsForRole
 * @param {string} tabKey - Tab key to check (must be in TAB_KEYS)
 * @returns {boolean} True if the role can access the tab
 */
export function canTab(perms, tabKey) {
  if (!TAB_KEYS.includes(tabKey)) {
    console.warn(`Invalid tab key: ${tabKey}`);
    return false;
  }
  return perms.tabs[tabKey] === true;
}

/**
 * Check if a role can perform a specific action
 * @param {object} perms - Permissions object from getPermissionsForRole
 * @param {string} actionKey - Action key to check (must be in ACTION_KEYS)
 * @returns {boolean} True if the role can perform the action
 */
export function canAction(perms, actionKey) {
  if (!ACTION_KEYS.includes(actionKey)) {
    console.warn(`Invalid action key: ${actionKey}`);
    return false;
  }
  return perms.actions[actionKey] === true;
}