/**
 * driverWriteEnforcement.ts
 *
 * Phase 8+ — Central Driver read-only enforcement logic.
 *
 * Enforces that normal UI workflows cannot create or update Driver records.
 * Only allowlisted compatibility services may write to Driver.
 *
 * Allowlisted compatibility write paths:
 *   - importDriversBulk
 *   - upsertOperationalEntry (writes driver_id as compatibility field)
 *   - upsertOperationalResult (writes driver_id as compatibility field)
 *   - recalculateStandings (writes driver_id as compatibility field)
 *   - repairDuplicateDriverRecords (explicit admin repair)
 *   - selectCanonicalDriverRecord (explicit admin repair)
 *   - mergeDuplicateDriversSafely (explicit admin repair)
 *   - createPersonIdentityFromDriver (migration helper)
 *   - repairDriverReferences (explicit admin repair)
 *   - backfillDriverNormalization (backfill helper)
 *   - backfillDriverCanonicalRoutingFields (backfill helper)
 *   - syncSourceAndEntityRecord (sync helper)
 *
 * These are server-side backend functions that run with service-role auth.
 * Client-supplied source_path values are NEVER trusted alone.
 */

// Allowlisted internal operation IDs that may write to Driver.
// These are backend function names, NOT client-supplied values.
export const ALLOWLISTED_DRIVER_WRITE_OPS = new Set([
  'importDriversBulk',
  'upsertOperationalEntry',
  'upsertOperationalResult',
  'upsertOperationalStanding',
  'recalculateStandings',
  'recalculateDriverCareerStats',
  'repairDuplicateDriverRecords',
  'selectCanonicalDriverRecord',
  'mergeDuplicateDriversSafely',
  'createPersonIdentityFromDriver',
  'repairDriverReferences',
  'backfillDriverNormalization',
  'backfillDriverCanonicalRoutingFields',
  'syncSourceAndEntityRecord',
  'autoGenerateDriverSlug',
  'autoMatchResultsToDrivers',
]);

// Event types for Driver write monitoring
export const DRIVER_WRITE_EVENTS = {
  BLOCKED_CREATE: 'blocked_driver_create',
  BLOCKED_UPDATE: 'blocked_driver_update',
  APPROVED_COMPAT_CREATE: 'approved_driver_compat_create',
  APPROVED_COMPAT_UPDATE: 'approved_driver_compat_update',
  ADMIN_REPAIR: 'driver_admin_repair',
  BLOCKED_COLLABORATOR_CREATE: 'blocked_driver_collaborator_create',
  ADAPTER_READ: 'driver_adapter_read',
};

/**
 * Check if an operation is allowlisted to write to Driver.
 * This is called server-side only — never trust client input.
 */
export function isAllowlistedDriverWrite(operationId) {
  return ALLOWLISTED_DRIVER_WRITE_OPS.has(operationId);
}

/**
 * Build a structured error response for blocked Driver writes.
 */
export function driverWriteBlockedError(operation, reason) {
  return {
    error: 'driver_write_blocked',
    message: `Driver write blocked: ${reason}`,
    operation,
    reason,
    driver_read_only: true,
  };
}

/**
 * Build a structured error response for deprecated Driver collaborator creation.
 */
export function driverCollaboratorDeprecatedError() {
  return {
    error: 'driver_collaborator_deprecated',
    message: 'Driver-based collaborator creation is deprecated. Use PersonIdentity or RacerProfile instead.',
    driver_read_only: true,
  };
}